import { useState } from 'react';
import { Link } from 'react-router-dom';
import Layout from '../components/Layout';
import { mockRiskAssessment, mockImages, mockFamilyHistory } from '../data/mockData';

const riskConfig = {
  Low: { color: '#22c55e', textColor: 'text-green-600', bgColor: 'bg-green-100', icon: 'check_circle', label: 'LOW' },
  Moderate: { color: '#de8712', textColor: 'text-[#de8712]', bgColor: 'bg-[#ffdcbd]', icon: 'warning', label: 'MODERATE' },
  High: { color: '#ba1a1a', textColor: 'text-[#ba1a1a]', bgColor: 'bg-[#ffdad6]', icon: 'dangerous', label: 'HIGH' },
};

export default function RiskAssessment() {
  const [hasAssessment, setHasAssessment] = useState(true);
  const [loading, setLoading] = useState(false);

  const riskLevel = mockRiskAssessment.risk_level;
  const config = riskConfig[riskLevel];
  const scorePercent = Math.round(mockRiskAssessment.generational_risk_score * 100);
  const hasFamilyCancer = mockFamilyHistory.some(f =>
    f.conditions.some(c => ['Breast Cancer', 'Ovarian Cancer', 'BRCA Gene Mutation'].includes(c))
  );

  const maternalMembers = mockFamilyHistory.filter(f => f.member_relation.includes('maternal'));
  const paternalMembers = mockFamilyHistory.filter(f => f.member_relation.includes('paternal'));

  const handleGenerate = () => {
    setLoading(true);
    setTimeout(() => { setLoading(false); setHasAssessment(true); }, 2000);
  };

  const conicGradient = `conic-gradient(${config.color} ${scorePercent}%, #dee3e9 0)`;

  return (
    <Layout>
      <div className="p-6 md:p-8 max-w-7xl mx-auto">
        <div className="mb-6">
          <h1 className="text-3xl font-bold text-[#171c20]" style={{ fontFamily: 'Manrope, sans-serif' }}>Risk Assessment Results</h1>
          <p className="text-[#3e4850] text-sm mt-1">Generated by Smart Health AI Clinical Analysis</p>
        </div>

        {!hasAssessment ? (
          <div className="bg-white rounded-2xl border border-[#bec8d2]/30 p-12 text-center">
            {loading ? (
              <div className="flex flex-col items-center gap-4">
                <div className="w-12 h-12 border-4 border-[#006591] border-t-transparent rounded-full animate-spin" />
                <p className="text-[#3e4850] text-sm">Calculating your risk profile...</p>
              </div>
            ) : (
              <>
                <span className="material-symbols-outlined text-[#3e4850]/40 text-6xl mb-4 block">analytics</span>
                <h2 className="text-xl font-bold text-[#171c20] mb-2" style={{ fontFamily: 'Manrope, sans-serif' }}>No risk assessment yet</h2>
                <p className="text-[#3e4850] text-sm mb-6 max-w-md mx-auto">Click below to generate your personalized risk assessment based on your symptoms, images, and family history.</p>
                <button onClick={handleGenerate} className="bg-[#006591] text-white font-bold px-8 py-3 rounded-xl hover:bg-[#005070] transition-colors">
                  Generate Risk Assessment
                </button>
              </>
            )}
          </div>
        ) : (
          <div className="space-y-6">
            {/* Overall Risk Card */}
            <div className="bg-white border border-[#bae6fd] rounded-2xl p-6 shadow-sm flex flex-col md:flex-row items-center gap-8">
              {/* Circular progress */}
              <div className="flex-shrink-0 relative w-48 h-48">
                <div
                  className="w-48 h-48 rounded-full flex items-center justify-center"
                  style={{ background: conicGradient }}
                >
                  <div className="w-36 h-36 rounded-full bg-white flex flex-col items-center justify-center">
                    <span className="text-3xl font-bold" style={{ color: config.color, fontFamily: 'Manrope, sans-serif' }}>{scorePercent}%</span>
                    <span className="text-xs text-[#3e4850] font-medium">SCORE</span>
                  </div>
                </div>
              </div>

              <div className="flex-1">
                <div className={`inline-flex items-center gap-2 ${config.bgColor} ${config.textColor} px-4 py-2 rounded-xl mb-4`}>
                  <span className="material-symbols-outlined text-2xl">{config.icon}</span>
                  <span className="text-3xl font-bold" style={{ fontFamily: 'Manrope, sans-serif' }}>{config.label}</span>
                </div>
                <p className="text-[#3e4850] text-sm leading-relaxed">
                  Based on the combined analysis of your recent symptom reports, radiological imaging, and identified hereditary markers, your current breast health risk profile is evaluated as {riskLevel.toLowerCase()}. Continuous monitoring is recommended.
                </p>
              </div>
            </div>

            {/* Hereditary Alert */}
            {hasFamilyCancer && (
              <div className="bg-[#ffdad6] border border-[#ba1a1a]/20 rounded-2xl p-5 flex items-start gap-4">
                <span className="material-symbols-outlined text-[#ba1a1a] text-3xl flex-shrink-0">genetics</span>
                <div>
                  <h3 className="font-bold text-[#93000a] mb-1" style={{ fontFamily: 'Manrope, sans-serif' }}>Generational Risk Alert</h3>
                  <p className="text-[#93000a] text-sm leading-relaxed">
                    Family Tree data indicates a high probability of inherited susceptibility to breast/ovarian cancer. This factor significantly contributes to the current risk assessment and warrants specialized preventative care.
                  </p>
                </div>
              </div>
            )}

            {/* Contributing Factors Grid */}
            <div className="grid md:grid-cols-3 gap-4">
              {/* Symptoms */}
              <div className="bg-[#f0f4fa] rounded-2xl p-5 border border-[#bec8d2]/30">
                <div className="flex items-center gap-2 mb-4">
                  <span className="material-symbols-outlined text-[#006591] text-xl">stethoscope</span>
                  <h3 className="font-bold text-[#171c20] text-sm" style={{ fontFamily: 'Manrope, sans-serif' }}>Symptoms</h3>
                </div>
                <div className="space-y-2">
                  {['Persistent breast pain for 14+ days', 'Reported lump in upper outer area', 'No reported fever or chills'].map((s, i) => (
                    <div key={i} className="flex items-start gap-2">
                      <span className="material-symbols-outlined text-[#de8712] text-sm mt-0.5">report_problem</span>
                      <p className="text-xs text-[#3e4850] leading-snug">{s}</p>
                    </div>
                  ))}
                </div>
              </div>

              {/* Image Analysis */}
              <div className="bg-[#f0f4fa] rounded-2xl p-5 border border-[#bec8d2]/30">
                <div className="flex items-center gap-2 mb-4">
                  <span className="material-symbols-outlined text-[#006591] text-xl">radiology</span>
                  <h3 className="font-bold text-[#171c20] text-sm" style={{ fontFamily: 'Manrope, sans-serif' }}>Image Analysis</h3>
                </div>
                <div className="w-full h-28 bg-[#dee3e9] rounded-xl flex items-center justify-center mb-3">
                  <span className="material-symbols-outlined text-[#3e4850]/40 text-3xl">radiology</span>
                </div>
                <p className="text-xs text-[#3e4850] leading-relaxed">{mockImages[0].ai_findings}</p>
              </div>

              {/* Hereditary Risk */}
              <div className="bg-[#f0f4fa] rounded-2xl p-5 border border-[#bec8d2]/30">
                <div className="flex items-center gap-2 mb-4">
                  <span className="material-symbols-outlined text-[#006591] text-xl">family_history</span>
                  <h3 className="font-bold text-[#171c20] text-sm" style={{ fontFamily: 'Manrope, sans-serif' }}>Hereditary Risk</h3>
                </div>
                <div className="space-y-2">
                  <div className="bg-white rounded-xl p-3 border border-[#bec8d2]/30">
                    <p className="text-xs font-semibold text-[#3e4850] uppercase tracking-wide mb-1">Maternal Lineage</p>
                    {maternalMembers.map(m => (
                      <p key={m.family_id} className="text-xs text-[#171c20]">{m.conditions.join(', ')} {m.notes && `(${m.notes})`}</p>
                    ))}
                  </div>
                  <div className="bg-white rounded-xl p-3 border border-[#bec8d2]/30">
                    <p className="text-xs font-semibold text-[#3e4850] uppercase tracking-wide mb-1">Paternal Lineage</p>
                    {paternalMembers.map(m => (
                      <p key={m.family_id} className="text-xs text-[#171c20]">{m.conditions.join(', ')} {m.notes && `(${m.notes})`}</p>
                    ))}
                  </div>
                </div>
              </div>
            </div>

            {/* Generational Risk Score */}
            <div className="bg-white border border-[#bae6fd] rounded-2xl p-6 shadow-sm">
              <div className="flex items-center justify-between mb-3">
                <h3 className="font-bold text-[#171c20]" style={{ fontFamily: 'Manrope, sans-serif' }}>Generational Risk Score</h3>
                <span className="text-3xl font-bold" style={{ color: config.color, fontFamily: 'Manrope, sans-serif' }}>{scorePercent}%</span>
              </div>
              <div className="w-full bg-[#f0f4fa] rounded-full h-4">
                <div className="h-4 rounded-full transition-all" style={{ width: `${scorePercent}%`, backgroundColor: config.color }} />
              </div>
              <div className="flex justify-between text-xs text-[#3e4850] mt-1">
                <span>Low Risk</span>
                <span>Moderate</span>
                <span>High Risk</span>
              </div>
            </div>

            {/* Recommended Action */}
            <div className="bg-[#0ea5e9]/10 border border-[#0ea5e9]/30 rounded-2xl p-5 flex items-start gap-3">
              <span className="material-symbols-outlined text-[#006591] text-2xl flex-shrink-0">lightbulb</span>
              <div>
                <h3 className="font-bold text-[#006591] mb-1 text-sm" style={{ fontFamily: 'Manrope, sans-serif' }}>Recommended Action</h3>
                <p className="text-sm text-[#3e4850] leading-relaxed">{mockRiskAssessment.recommended_action}</p>
              </div>
            </div>

            {/* Recommended Actions Grid */}
            <div>
              <h2 className="text-xl font-bold text-[#171c20] mb-4" style={{ fontFamily: 'Manrope, sans-serif' }}>Recommended Actions</h2>
              <div className="grid md:grid-cols-3 gap-4">
                {[
                  {
                    icon: 'person_search',
                    title: 'Breast Oncologist',
                    desc: 'Schedule an evaluation with a breast cancer specialist.',
                    btn: 'Book Appointment',
                    to: '/search-specialist',
                  },
                  {
                    icon: 'local_hospital',
                    title: 'Local Hospital',
                    desc: 'Find nearest facility with advanced imaging capabilities.',
                    btn: 'Find Facility',
                    to: '/search-specialist',
                  },
                  {
                    icon: 'video_camera_front',
                    title: 'Tele-Consultation',
                    desc: 'Connect with an on-call physician immediately.',
                    btn: 'Start Session',
                    to: '/consultation-chat/c-001',
                  },
                ].map((card) => (
                  <div key={card.title} className="bg-white border border-[#bae6fd] rounded-2xl p-5 hover:shadow-md transition-shadow">
                    <div className="w-12 h-12 bg-[#bae6fd] rounded-2xl flex items-center justify-center mb-4">
                      <span className="material-symbols-outlined text-[#006591] text-xl">{card.icon}</span>
                    </div>
                    <h3 className="font-bold text-[#171c20] mb-2" style={{ fontFamily: 'Manrope, sans-serif' }}>{card.title}</h3>
                    <p className="text-xs text-[#3e4850] leading-relaxed mb-4">{card.desc}</p>
                    <Link
                      to={card.to}
                      className="w-full flex items-center justify-center border border-[#006591] text-[#006591] font-bold py-2.5 rounded-xl hover:bg-[#006591]/10 transition-colors text-sm"
                    >
                      {card.btn}
                    </Link>
                  </div>
                ))}
              </div>
            </div>
          </div>
        )}
      </div>
    </Layout>
  );
}
